name: Move pull requests to project

on:
  pull_request:
    types: [opened]
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: LTPS Management
          column: Review in progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
