name: Move pull requests to project

on:
  pull_request_target:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: LTPS Management
          column-name: Review in progress
          issue-number: ${{ github.event.number }}
